spring:
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3333/impact_us
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


api:
  security:
    token:
      secret: ${JWT_SECRET:12345678}