name: CI

on:
  push:
    branches:
      - master

jobs:
  name: continuous integration
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
      - name: Build and test
        run: mvn clean install